/* eslint-disable prettier/prettier */
export default [
  {
    param_10670: '4',
    param_7608: 'С пробегом',
    avitoid: '2125526252',
    coords: ['Object'],
    city: 'Санкт-Петербург',
    param_10365: '',
    person_type: 'Частное лицо (фильтр)',
    source: 'avito.ru',
    metro: 'Озерки',
    url: 'https://www.avito.ru/sankt-peterburg/avtomobili/acura_tl_2005_2125526252',
    cat1_id: 21,
    description:
      'Продам автомобиль бизнес класса который сочетает в себе комфорт, мощь и надежность, заинтересовавшимся расскажу все  по телефону, машина обслужина для своих лет в отличном состоянии , без ржавчины',
    param_7610: 'Не битый',
    param_7622: 'TL',
    nedvigimost_type: 'Продам',
    price: 600000,
    cat2: 'Автомобили',
    param_10378: 'Автомат',
    contactname: '',
    phone_protected: 1,
    param_10609: '2005',
    cat1: 'Транспорт',
    id: 537556112,
    param_7614: 'Acura',
    param_10527: 'Левый',
    km_do_metro: 0,
    person: 'недоступно',
    address: '',
    cat2_id: 22,
    param_10523: 'Передний',
    param_10383: 'Бензин',
    time: '2021-03-28 21:33:13',
    title: 'Acura TL 3.2 AT, 2005, 280 000 км',
    param_12725: '280 000',
    param_12846: '4+',
    images: [{"imgurl":"https://02.img.avito.st/image/1/p1VhhLaxC7xXM4mxI_67TJknC7jdJQG-"},{"imgurl":"https://91.img.avito.st/image/1/stZAGraxHj92rZwyKGCuz7i5Hjv8uxQ9"},{"imgurl":"https://33.img.avito.st/image/1/HJiw7LaxsHGGWzJ8hLwdgUhPsHUMTbpz"},{"imgurl":"https://96.img.avito.st/image/1/qQQDaraxBe013YfgXRC1HfvJBem_yw_v"},{"imgurl":"https://93.img.avito.st/image/1/rKTLDbaxAE39uoJAn3ewvTOuAEl3rApP"},{"imgurl":"https://01.img.avito.st/image/1/pJYY7LaxCH8uW4pyXJa4j-BPCHukTQJ9"},{"imgurl":"https://70.img.avito.st/image/1/l1I3hLaxO7sBM7m2FdKWS88nO7-LJTG5"},{"imgurl":"https://66.img.avito.st/image/1/Mw5k2Laxn-dSbx3qDrQtF5x7n-PYeZXl"},{"imgurl":"https://68.img.avito.st/image/1/LRLCPbaxgfv0igP2lFEzCzqegf9-nIv5"},{"imgurl":"https://85.img.avito.st/image/1/tKTLDbaxGE39uppAr3eovTOuGEl3rBJP"},{"imgurl":"https://67.img.avito.st/image/1/jjSfMLaxIt2ph6DQj0KQLWeTItkjkSjf"},{"imgurl":"https://74.img.avito.st/image/1/h7iRHbaxK1Gnqqlck2-ZoWm-K1UtvCFT"},{"imgurl":"https://64.img.avito.st/image/1/jRL6PbaxIfvMiqP27E-TCwKeIf9GnCv5"},{"imgurl":"https://33.img.avito.st/image/1/SCHSVLax5Mjk42bFziVWOCr35Mxu9e7K"},{"imgurl":"https://98.img.avito.st/image/1/r8wI8LaxAyU-R4EoWoKx1fBTAyG0UQkn"},{"imgurl":"https://63.img.avito.st/image/1/bnhpiraxwpFfPUCcOftwYZEpwpXVK8iT"},{"imgurl":"https://02.img.avito.st/image/1/q5BTkbaxB3llJoV0CeO1iasyB33vMA17"},{"imgurl":"https://75.img.avito.st/image/1/hsIlfLaxKisTy6gmJQ6Y293fKi-Z3SAp"},{"imgurl":"https://40.img.avito.st/image/1/QSJZN7ax7ctvgG_GV0ZfO6GU7c_llufJ"},{"imgurl":"https://73.img.avito.st/image/1/YCHSVLaxzMjk407FniV-OCr3zMxu9cbK"},{"imgurl":"https://53.img.avito.st/image/1/dKTKBbax2E38slpArnRqvTKm2El2pNJP"},{"imgurl":"https://82.img.avito.st/image/1/Gw6E2Laxt-eybzXqvqgFF3x7t-M4eb3l"},{"imgurl":"https://36.img.avito.st/image/1/RacoWrax6U4e7WtDLitbvtD56UqU--NM"},{"imgurl":"https://80.img.avito.st/image/1/GX9_TLaxtZZJ-zebQTwHZofvtZLD7b-U"}],
    param_10675: '3.2',
    phone: '896749XXXXX',
    param_10530: 'Серебряный',
    person_type_id: 3,
    nedvigimost_type_id: '1',
    source_id: 1,
    region: 'Санкт-Петербург',
    city1: 'Санкт-Петербург',
    phone_operator: 'МТТ',
    phone_region: 'г. Санкт-Петербург и Ленинградская область',
    params: {
      'Количество дверей': '4',
      'Тип автомобиля': 'С пробегом',
      'Тип кузова': '',
      'Состояние': 'Не битый',
      'Модель': 'TL',
      'Коробка передач': 'Автомат',
      'Год выпуска': '2005',
      'Марка': 'Acura',
      'Руль': 'Левый',
      'Привод': 'Передний',
      'Тип двигателя': 'Бензин',
      'Пробег': '280 000',
      'Владельцев по ПТС': '4+',
      'Объём двигателя, л': '3.2',
      'Цвет': 'Серебряный'
    },
    count_ads_same_phone: null
  },
  {
    param_10670: '4',
    param_7608: 'С пробегом',
    avitoid: '2125526252',
    coords: ['Object'],
    city: 'Санкт-Петербург',
    param_10365: '',
    person_type: 'Частное лицо (фильтр)',
    source: 'avito.ru',
    metro: 'Озерки',
    url: 'https://www.avito.ru/sankt-peterburg/avtomobili/acura_tl_2005_2125526252',
    cat1_id: 21,
    description:
      'Продам автомобиль бизнес класса который сочетает в себе комфорт, мощь и надежность, заинтересовавшимся расскажу все  по телефону, машина обслужина для своих лет в отличном состоянии , без ржавчины',
    param_7610: 'Не битый',
    param_7622: 'TL',
    nedvigimost_type: 'Продам',
    price: 600000,
    cat2: 'Автомобили',
    param_10378: 'Автомат',
    contactname: '',
    phone_protected: 1,
    param_10609: '2005',
    cat1: 'Транспорт',
    id: 537556112,
    param_7614: 'Acura',
    param_10527: 'Левый',
    km_do_metro: 0,
    person: 'недоступно',
    address: '',
    cat2_id: 22,
    param_10523: 'Передний',
    param_10383: 'Бензин',
    time: '2021-03-28 21:33:13',
    title: 'Acura TL 3.2 AT, 2005, 280 000 км',
    param_12725: '280 000',
    param_12846: '4+',
    images: [{"imgurl":"https://02.img.avito.st/image/1/p1VhhLaxC7xXM4mxI_67TJknC7jdJQG-"},{"imgurl":"https://91.img.avito.st/image/1/stZAGraxHj92rZwyKGCuz7i5Hjv8uxQ9"},{"imgurl":"https://33.img.avito.st/image/1/HJiw7LaxsHGGWzJ8hLwdgUhPsHUMTbpz"},{"imgurl":"https://96.img.avito.st/image/1/qQQDaraxBe013YfgXRC1HfvJBem_yw_v"},{"imgurl":"https://93.img.avito.st/image/1/rKTLDbaxAE39uoJAn3ewvTOuAEl3rApP"},{"imgurl":"https://01.img.avito.st/image/1/pJYY7LaxCH8uW4pyXJa4j-BPCHukTQJ9"},{"imgurl":"https://70.img.avito.st/image/1/l1I3hLaxO7sBM7m2FdKWS88nO7-LJTG5"},{"imgurl":"https://66.img.avito.st/image/1/Mw5k2Laxn-dSbx3qDrQtF5x7n-PYeZXl"},{"imgurl":"https://68.img.avito.st/image/1/LRLCPbaxgfv0igP2lFEzCzqegf9-nIv5"},{"imgurl":"https://85.img.avito.st/image/1/tKTLDbaxGE39uppAr3eovTOuGEl3rBJP"},{"imgurl":"https://67.img.avito.st/image/1/jjSfMLaxIt2ph6DQj0KQLWeTItkjkSjf"},{"imgurl":"https://74.img.avito.st/image/1/h7iRHbaxK1Gnqqlck2-ZoWm-K1UtvCFT"},{"imgurl":"https://64.img.avito.st/image/1/jRL6PbaxIfvMiqP27E-TCwKeIf9GnCv5"},{"imgurl":"https://33.img.avito.st/image/1/SCHSVLax5Mjk42bFziVWOCr35Mxu9e7K"},{"imgurl":"https://98.img.avito.st/image/1/r8wI8LaxAyU-R4EoWoKx1fBTAyG0UQkn"},{"imgurl":"https://63.img.avito.st/image/1/bnhpiraxwpFfPUCcOftwYZEpwpXVK8iT"},{"imgurl":"https://02.img.avito.st/image/1/q5BTkbaxB3llJoV0CeO1iasyB33vMA17"},{"imgurl":"https://75.img.avito.st/image/1/hsIlfLaxKisTy6gmJQ6Y293fKi-Z3SAp"},{"imgurl":"https://40.img.avito.st/image/1/QSJZN7ax7ctvgG_GV0ZfO6GU7c_llufJ"},{"imgurl":"https://73.img.avito.st/image/1/YCHSVLaxzMjk407FniV-OCr3zMxu9cbK"},{"imgurl":"https://53.img.avito.st/image/1/dKTKBbax2E38slpArnRqvTKm2El2pNJP"},{"imgurl":"https://82.img.avito.st/image/1/Gw6E2Laxt-eybzXqvqgFF3x7t-M4eb3l"},{"imgurl":"https://36.img.avito.st/image/1/RacoWrax6U4e7WtDLitbvtD56UqU--NM"},{"imgurl":"https://80.img.avito.st/image/1/GX9_TLaxtZZJ-zebQTwHZofvtZLD7b-U"}],
    param_10675: '3.2',
    phone: '896749XXXXX',
    param_10530: 'Серебряный',
    person_type_id: 3,
    nedvigimost_type_id: '1',
    source_id: 1,
    region: 'Санкт-Петербург',
    city1: 'Санкт-Петербург',
    phone_operator: 'МТТ',
    phone_region: 'г. Санкт-Петербург и Ленинградская область',
    params: {
      'Количество дверей': '4',
      'Тип автомобиля': 'С пробегом',
      'Тип кузова': '',
      'Состояние': 'Не битый',
      'Модель': 'TL',
      'Коробка передач': 'Автомат',
      'Год выпуска': '2005',
      'Марка': 'Acura',
      'Руль': 'Левый',
      'Привод': 'Передний',
      'Тип двигателя': 'Бензин',
      'Пробег': '280 000',
      'Владельцев по ПТС': '4+',
      'Объём двигателя, л': '3.2',
      'Цвет': 'Серебряный'
    },
    count_ads_same_phone: null
  }
];
