// eslint-disable-next-line no-undef
const container = new Map();
import AutoAdsApiAdapter from './adapters/AutoAdsApiAdapter.mjs';
import DefaultAdsApiAdapter from './adapters/DefaultAdsApiAdapter.mjs';
import AdsAdapterFactory from './adapters/AdsAdapterFactory.mjs';
import DataSource from './database/DataSource.mjs';
import RegionService from './services/RegionService.mjs';
import CategoryService from './services/CategoryService.mjs';
import AdsApiProvider from './providers/AdsApiProvider.mjs';
import LastDateRepository from './repositories/LastDateRepository.mjs';
import AdsRepository from './repositories/AdsRepository.mjs';
import CategoryRepository from './repositories/CategoryRepository.mjs';
import RegionRepository from './repositories/RegionRepository.mjs';
import DictionaryRepository from './repositories/DictionaryRepository.mjs';
import CatalogProvider from './providers/CatalogProvider.mjs';
import CatalogAdapter from './adapters/CatalogAdapter.mjs';
import CatalogRepository from './repositories/CatalogRepository.mjs';
import ModelRepository from './repositories/ModelRepository.mjs';
import ManufacturerRepository from './repositories/ManufacturerRepository.mjs';
import ModificationRepository from './repositories/ModificationRepository.mjs';
import TransmissionRepository from './repositories/TransmissionRepository.mjs';
import BodyRepository from './repositories/BodyRepository.mjs';
import ManufacturerMapper from './mappers/ManufacturerMapper.mjs';
import ModificationMapper from './mappers/ModificationMapper.mjs';
import ModelMapper from './mappers/ModelMapper.mjs';

container.set('autoAdsApiAdapter', AutoAdsApiAdapter);
container.set('defaultAdsApiAdapter', DefaultAdsApiAdapter);
container.set('dataSource', DataSource);
container.set('adsAdapterFactory', AdsAdapterFactory);
container.set('regionService', RegionService);
container.set('categoryService', CategoryService);
container.set('adsProvider', AdsApiProvider);
container.set('lastDateRepository', LastDateRepository);
container.set('adsRepository', AdsRepository);
container.set('categoryRepository', CategoryRepository);
container.set('regionRepository', RegionRepository);
container.set('dictionaryRepository', DictionaryRepository);
container.set('catalogProvider', CatalogProvider);
container.set('catalogAdapter', CatalogAdapter);
container.set('catalogRepository', CatalogRepository);
container.set('modelRepository', ModelRepository);
container.set('manufacturerRepository', ManufacturerRepository);
container.set('modificationRepository', ModificationRepository);
container.set('transmissionRepository', TransmissionRepository);
container.set('bodyRepository', BodyRepository);
container.set('modelMapper', ModelMapper);
container.set('modificationMapper', ModificationMapper);
container.set('manufacturerMapper', ManufacturerMapper);

export default container;
