CREATE TABLE
IF NOT EXISTS ADS
(
      id INT AUTO_INCREMENT PRIMARY KEY,
      type VARCHAR
(100),
      category VARCHAR
(100),
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at 
        TIMESTAMP 
        NOT NULL 
        DEFAULT CURRENT_TIMESTAMP 
        ON
UPDATE CURRENT_TIMESTAMP
)